### ISSUE TITLE
Goal R

### ISSUE THREAD

**Issue by Ranjanirr** [End-to-end-provenance/RDataTracker#625] opened 2020-06-03 02:39 UTC
> library (rdtLite)
> prov.init("goooooaaaaallllll.Rmd", prov.dir = ".",overwrite = FALSE)
> knitr::opts_chunk$set(echo = TRUE,message=FALSE,warning=FALSE)
> 
> 
> library(ggplot2)
> library(dplyr)
> library(gridExtra)
> library(RColorBrewer)
> library(ggthemes)
> library(viridis)
> library(reshape2)
> library(gridExtra)
> library(scales)
> library(ggalluvial)
> library(knitr)
> library(DT)
> library(psych)
> library(rpart)
> library(rpart.plot)
> options(DT.options = list(pageLength = 4))
> 
> worldCups <- read.csv('WorldCups.csv',sep=',',stringsAsFactors=F)
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> worldCups$Attendance <- sapply(worldCups$Attendance, function(x) as.numeric(gsub("\\.","",x)))
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> worldCups$DateTS <- as.Date(paste0(worldCups$Year,'-01-01'))
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> #head(worldCups)
> 
> countries <-unique(sort(append(unique(worldCups$Winner),unique(worldCups$Country))))
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> cols<-colorRampPalette(brewer.pal(9,'Set1'))(length(countries))
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> COLS <- data.frame(color = cols, country = countries)
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> COLS$color <- as.character(COLS$color)
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> COLS$country <- as.character(COLS$country)
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> COLS$index <- 1:nrow(COLS)
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> 
> worldCups$CountryColor <- sapply(worldCups$Country, function(x) COLS$color[match(x,COLS$country)])
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> # adding winner country color
> worldCups$WinnerColor <- sapply(worldCups$Winner, function(x) COLS$color[match(x,COLS$country)])
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> 
> myleg<- COLS %>% ggplot(aes(x=reorder(country,-index),y=1)) + 
+   geom_bar(stat='identity',aes(fill=color)) + 
+   coord_flip() + scale_fill_identity()+ 
+   theme_fivethirtyeight() + 
+   theme(panel.grid= element_blank() ,axis.text.x = element_blank())
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> 
> lims <- as.POSIXct(strptime(c("1927-01-01","2015-01-01"), format = "%Y-%m-%d"))
> # plotof goals vs year
> g1 <- worldCups %>% ggplot(aes(x=as.POSIXct(DateTS),y=GoalsScored)) + 
+   geom_vline(xintercept= as.POSIXct(as.Date('1930-01-01')),alpha=.5) + 
+   geom_vline(xintercept= as.POSIXct(as.Date('1934-01-01')),alpha=.5) + 
+   geom_vline(xintercept= as.POSIXct(as.Date('1966-01-01')),alpha=.5) + 
+   geom_vline(xintercept= as.POSIXct(as.Date('1978-01-01')),alpha=.5) + 
+   geom_vline(xintercept= as.POSIXct(as.Date('1998-01-01')),alpha=.5) + 
+   geom_line(alpha=.1,size=4) + 
+   geom_point(aes(color=WinnerColor),size=4) + 
+   theme_fivethirtyeight() + 
+   scale_x_datetime(limits =lims, date_breaks="4 year", labels = date_format("%Y")) + 
+   scale_color_identity()
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> # add the legend plot
> g11 <- g1 + annotation_custom( ggplotGrob(myleg), 
+                                xmin=as.numeric(as.POSIXct(as.Date('1922-01-01'))),
+                                xmax=as.numeric(as.POSIXct(as.Date('1936-01-01'))),
+                                ymin=90,ymax=180) + 
+   labs(title='Total Goals scored per World Cup')
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> # plot of Attendance vs year                    
> g2 <- worldCups %>% ggplot(aes(x=as.POSIXct(DateTS),y=Attendance)) + 
+   geom_vline(xintercept= as.POSIXct(as.Date('1930-01-01')),alpha=.5) + 
+   geom_vline(xintercept= as.POSIXct(as.Date('1934-01-01')),alpha=.5) + 
+   geom_vline(xintercept= as.POSIXct(as.Date('1966-01-01')),alpha=.5) + 
+   geom_vline(xintercept= as.POSIXct(as.Date('1978-01-01')),alpha=.5) + 
+   geom_vline(xintercept= as.POSIXct(as.Date('1998-01-01')),alpha=.5) + 
+   geom_line(alpha=.1,size=4) + 
+   geom_point(aes(color=CountryColor),size=4) + 
+   theme_fivethirtyeight() + 
+   theme(axis.text.y =element_text(angle=75),axis.text.x=element_text(size=11)) +
+   scale_x_datetime(
+     limits =lims, 
+     date_breaks="4 year", 
+     labels = date_format("%Y")) +
+   scale_color_identity() + theme(axis.text.x=element_blank()) + labs(
+     title='Attendance per World Cup',
+     subtitle='vertical lines show editions for which the host country also won')
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> 
> grid.arrange(g2,g11,ncol=1)
> 
> matchesPlayed<-worldCups %>% ggplot(aes(x=as.POSIXct(DateTS),y= MatchesPlayed)) + 
+   geom_vline(xintercept= as.POSIXct(as.Date('1930-01-01')),size=1.5,alpha=1,color='red') + 
+   geom_vline(xintercept= as.POSIXct(as.Date('1934-01-01')),size=1.5,alpha=1,color='darkgreen') + 
+   geom_vline(xintercept= as.POSIXct(as.Date('1938-01-01')),size=1.5,alpha=1,color='darkgreen') + 
+   geom_vline(xintercept= as.POSIXct(as.Date('1950-01-01')),size=1.5,alpha=1,color='blue') + 
+   geom_vline(xintercept= as.POSIXct(as.Date('1954-01-01')),size=1.5,alpha=1,color='gold') + 
+   geom_vline(xintercept= as.POSIXct(as.Date('1970-01-01')),size=1.5,alpha=1,color='gold') + 
+   geom_vline(xintercept= as.POSIXct(as.Date('1974-01-01')),size=1.5,alpha=1,color='darkolivegreen') +
+   geom_vline(xintercept= as.POSIXct(as.Date('1978-01-01')),size=1.5,alpha=1,color='darkolivegreen') +
+   geom_vline(xintercept= as.POSIXct(as.Date('1982-01-01')),size=1.5,alpha=1,color='purple') +
+   geom_vline(xintercept= as.POSIXct(as.Date('1986-01-01')),size=1.5,alpha=1,color='salmon') +
+   geom_vline(xintercept= as.POSIXct(as.Date('1994-01-01')),size=1.5,alpha=1,color='salmon') + 
+   geom_vline(xintercept= as.POSIXct(as.Date('1998-01-01')),size=1.5,alpha=1,color='black') +
+   geom_vline(xintercept= as.POSIXct(as.Date('2014-01-01')),size=1.5,alpha=1,color='black') +
+   geom_line(alpha=.2,size=3) + geom_point(size=3) + theme_fivethirtyeight() +
+   scale_x_datetime(limits =lims, date_breaks="4 year", labels = date_format("%Y")) + 
+   labs(title='Matches played',subtitle='Lines denote the changes in the format of each final tournament:\nhttps://en.wikipedia.org/wiki/History_of_the_FIFA_World_Cup') +
+   theme(axis.text.x=element_blank())
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> 
> qualifiedTeams<-worldCups %>% ggplot(aes(x=as.POSIXct(DateTS),y= QualifiedTeams)) + 
+   geom_vline(xintercept= as.POSIXct(as.Date('1930-01-01')),size=1.5,alpha=1,color='red') + 
+   geom_vline(xintercept= as.POSIXct(as.Date('1934-01-01')),size=1.5,alpha=1,color='darkgreen') + 
+   geom_vline(xintercept= as.POSIXct(as.Date('1938-01-01')),size=1.5,alpha=1,color='darkgreen') + 
+   geom_vline(xintercept= as.POSIXct(as.Date('1950-01-01')),size=1.5,alpha=1,color='blue') + 
+   geom_vline(xintercept= as.POSIXct(as.Date('1954-01-01')),size=1.5,alpha=1,color='gold') + 
+   geom_vline(xintercept= as.POSIXct(as.Date('1970-01-01')),size=1.5,alpha=1,color='gold') + 
+   geom_vline(xintercept= as.POSIXct(as.Date('1974-01-01')),size=1.5,alpha=1,color='darkolivegreen') +
+   geom_vline(xintercept= as.POSIXct(as.Date('1978-01-01')),size=1.5,alpha=1,color='darkolivegreen') +
+   geom_vline(xintercept= as.POSIXct(as.Date('1982-01-01')),size=1.5,alpha=1,color='purple') +
+   geom_vline(xintercept= as.POSIXct(as.Date('1986-01-01')),size=1.5,alpha=1,color='salmon') +
+   geom_vline(xintercept= as.POSIXct(as.Date('1994-01-01')),size=1.5,alpha=1,color='salmon') + 
+   geom_vline(xintercept= as.POSIXct(as.Date('1998-01-01')),size=1.5,alpha=1,color='black') +
+   geom_vline(xintercept= as.POSIXct(as.Date('2014-01-01')),size=1.5,alpha=1,color='black') +
+   geom_line(alpha=.2,size=3) + geom_point(size=3) + 
+   theme_fivethirtyeight() + 
+   scale_x_datetime(limits =lims, date_breaks="4 year", labels = date_format("%Y")) + 
+   scale_color_identity() + labs(title='Qualified teams') + 
+   theme(axis.text.x=element_text(size=11))
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> 
> grid.arrange(matchesPlayed, qualifiedTeams,ncol=1)
> 
> matches <-read.csv('WorldCupMatches.csv',sep=',',stringsAsFactors=F)
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> 
> na_count <- data.frame(sapply(matches, function(y) sum(length(which(is.na(y))))))
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> colnames(na_count)<-'number'
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> names <- rownames(na_count)
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> rownames(na_count) <- NULL
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> na_count <- cbind(names,na_count)
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> na_count$Percentage <- (na_count$number / nrow(matches)) * 100
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> na_count$Percent <-paste0(round(na_count$Percentage,1),"")
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> 
> ggplot(data=na_count,aes(x=reorder(names,-number),y=number)) + 
+   geom_histogram(stat='identity') + theme_fivethirtyeight() + 
+   theme(axis.text.x = element_text(angle=45, hjust=1)) + 
+   ylab('Number of rows') + xlab('features') +
+   geom_text(aes(label=Percent), position=position_dodge(width=0.9), hjust=0.25,vjust=-0.25,size=4,color='red') + 
+   labs(title='Missing values in dataset',subtitle='percentage in red')
Warning: Ignoring unknown parameters: binwidth, bins, pad
Error in snapshot.size * 1024 : non-numeric argument to binary operator
> 
> matches <- matches %>% na.omit()
> matches$Away.Team.Name <-ifelse(matches$Away.Team.Name =='IR Iran','Iran',matches$Away.Team.Name)
> matches$Home.Team.Name <-ifelse(matches$Home.Team.Name =='IR Iran','Iran',matches$Home.Team.Name)
> 
> matches[matches$Home.Team.Name=="" & matches$Year==1986,'Home.Team.Name']<-'Northern Ireland'
> matches[matches$Away.Team.Name=="" & matches$Year==1986,'Away.Team.Name']<-'Northern Ireland'
> matches[matches$Away.Team.Name=="" & matches$Year==1982 & matches$Stage=='Group 5','Away.Team.Name']<-'Northern Ireland'
> matches[matches$Home.Team.Name=="" & matches$Year==1982 & matches$Stage=='Group 5','Away.Home.Name']<-'Northern Ireland'
> 
> matches <- matches[!(matches$Away.Team.Name=="" & matches$Year==1982 & matches$Stage=='Group 4'),]
> 
> makeFinalScore<-function(team1, team2, score1, score2, free1, free2){
+   # decision made within time
+   if(score1 != score2){
+     if(score1 > score2){
+       return(team1)
+     }
+     else if(score2>score1){
+       return(team2)
+     }
+   }
+   # decision made with free kicks
+   else{
+     if(free1 > free2){
+       return(team1)
+     }
+     else if(free2>free1){
+       return(team2)
+     }
+   }
+ }
> 
> worldCup <- list()
> cnt <- 0
> 
> for (edition in seq(1986,2014,4)){
+   cnt <- cnt + 1
+   tempo <- data.frame(matches %>% dplyr::filter(Year == edition & (!grepl('Group',Stage) & !grepl('Play-off',Stage))))
+   tempo$Team_1_Score <- sapply(tempo$Win.conditions, function(x) as.numeric(trimws(strsplit(gsub(".*\\((.*)\\).*","\\1",x),"-")[[1]])[1]))
+   tempo$Team_2_Score <- sapply(tempo$Win.conditions, function(x) as.numeric(trimws(strsplit(gsub(".*\\((.*)\\).*","\\1",x),"-")[[1]])[2]))
+   tempo$gameWinner <- mapply(makeFinalScore, tempo$Home.Team.Name,tempo$Away.Team.Name, tempo$Home.Team.Goals, tempo$Away.Team.Goals, tempo$Team_1_Score, tempo$Team_2_Score)
+   worldCup[[cnt]] <- tempo
+ }
There were 21 warnings (use warnings() to see them)
> prov.quit()

**Comment by Ranjanirr** [comment] 2020-06-08 14:17
Kaggle = GOOOOOAAAAALLLLLL !!!!!!!!!!!!

**Comment by blernermhc** [comment] 2020-06-22 18:57
Duplicate of issue #628

**Closed by blernermhc** 2020-06-22 18:57 UTC
