### ISSUE TITLE
Data nodes of existing variables before execution does not exist

### ISSUE THREAD

**Issue by fong22e** [End-to-end-provenance/RDataTracker#602] opened 2019-12-24 00:47 UTC
While working on the debugger, I noticed that data nodes of variables that are in `GlobalEnv` before the execution of a script using `prov.run` are not recorded as data nodes. This occurs in both `rdt` and `rdtLite`.

For example, in the console:
```
x <- 55
rdtLite::prov.run("test2.R")
```
In `test2.R`:
```
y <- x + 3
```
The data node for `x` does not exist.

**Comment by erboose** [comment] 2019-12-24 15:54
Looks like the problem may be in the .ddg.data.node.exists function in DataNodes.R.  ddg.initial.env is a data frame that contains values bound in the global environment before the script runs.  So instead of:

if (exists(dname, .ddg.get("ddg.initial.env")))

We might say something like:

if (length(which(.ddg.get("ddg.initial.env") == dname)) > 0)

Once fixed, we might want to add a regression test for this feature, if possible.

**Comment by fong22e** [comment] 2019-12-24 17:17
Would it be better to put these nodes in the general data nodes table instead? It seems like it could be easier to keep track of all data nodes if they are in the same table.

**Comment by erboose** [comment] 2019-12-24 20:48
They are (or should be) in the data table as well.

Sent from my iPhone

On Dec 24, 2019, at 12:17 PM, Elizabeth Fong <notifications@github.com> wrote:

﻿

Would it be better to put these nodes in the general data nodes table instead? It seems like it could be easier to keep track of all data nodes if they are in the same table.

**Comment by erboose** [comment] 2020-01-10 22:06
Fixed in from.env branch.

**Closed by erboose** 2020-01-10 22:06 UTC
Labels: bug, high priority
