### ISSUE TITLE
Problems with current version of development

### ISSUE THREAD

**Issue by erboose** [End-to-end-provenance/RDataTracker#296] opened 2017-06-05 19:05 UTC
The following problems were observed with the current version of development (6/5/2017):

met-real-time.R:  Input and output file nodes are orphaned (no edges).

hydro-real-time.R:  DDG Explorer is unable to load ddg.json or ddg.txt.

These problems appear to be new and do not occur with the current version of master.

**Comment by tfjmp** [comment] 2017-06-05 20:20
Would you mind uploading the JSON generated for those two examples?

**Comment by tfjmp** [comment] 2017-06-05 20:59
[met-real-time-ddg.txt](https://github.com/End-to-end-provenance/RDataTracker/files/1053177/met-real-time-ddg.txt)
![isitoutput](https://cloud.githubusercontent.com/assets/1970355/26802786/c268d948-4a39-11e7-9ce7-8ec79ba8f697.png)

Thanks @erboose ! Is this the output file?

The other one seems ok here:
![hydro](https://cloud.githubusercontent.com/assets/1970355/26802911/39231b70-4a3a-11e7-8143-fde312d34e60.png)

It may be a problem with DDG Explorer rather than RDataTracker?

**Comment by fong22e** [comment] 2017-06-06 20:40
There is definitely a problem with the DDGExplorer .txt parser. I am not sure if this is caused by that problem, but fixing the parser is on my todo list!

**Comment by tfjmp** [comment] 2017-06-06 20:45
@fong22e according to @erboose the problem seems to occur also with the JSON. Should we open an issue in DDG Explorer and close this one? The JSON seems perfectly valid.

**Comment by fong22e** [comment] 2017-06-06 20:46
Yes, that is a good idea. The .json parser must also be broken.

**Comment by tfjmp** [comment] 2017-06-06 20:50
Opened an issue in DDG-Explorer, closing this one.

**Closed by tfjmp** 2017-06-06 20:50 UTC
Labels: bug
