### ISSUE TITLE
Very Small R

### ISSUE THREAD

**Issue by Ranjanirr** [End-to-end-provenance/RDataTracker#627] opened 2020-06-03 03:38 UTC
> library(rdtLite)
> prov.init("VerySmall.R", prov.dir = ".", overwrite = FALSE)
> library(ggplot2)
> my.data.frame2 <- read.csv("prescriptions_copy.csv", header = FALSE)
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> colnames(my.data.frame2) <- c("Year", "All_Pharmacotherapy_Prescriptions", "Nicotine_Replacement_Therapy_Prescriptions", "Bupropoin (Zyban) Prescriptions", "Varenicline (Champix) Prescriptions", "Net_Ingredient_Cost_of_All_Pharmacotherapies", "Net Ingredient Cost of All Nicotine Replacement Therapies (NRT)", "Net Ingredient Cost of Bupropion (Zyban)", "Net Ingredient Cost of Varenicline (Champix)")
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> #print(my.data.frame)
> prescriptions =(my.data.frame2$All_Pharmacotherapy_Prescriptions)
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> nicotine = (my.data.frame2$Nicotine_Replacement_Therapy_Prescriptions)
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> ingredient = (my.data.frame2$Net_Ingredient_Cost_of_All_Pharmacotherapies)
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> print(prescriptions)
 [1] All Pharmacotherapy Prescriptions 1348                             
 [3] 1778                              2203                             
 [5] 2532                              2564                             
 [7] 2483                              2263                             
 [9] 2475                              2079                             
[11] 2205                              2044                             
12 Levels: 1348 1778 2044 2079 2203 2205 2263 2475 2483 2532 ... All Pharmacotherapy Prescriptions
> print(nicotine)
 [1] Nicotine Replacement Therapy (NRT) Prescriptions
 [2] 766                                             
 [3] 1059                                            
 [4] 1318                                            
 [5] 1545                                            
 [6] 1541                                            
 [7] 1559                                            
 [8] 1492                                            
 [9] 1756                                            
[10] 1938                                            
[11] 2076                                            
[12] 1908                                            
12 Levels: 1059 1318 1492 1541 1545 1559 1756 1908 1938 2076 ... Nicotine Replacement Therapy (NRT) Prescriptions
> print(ingredient)
 [1] Net Ingredient Cost of All Pharmacotherapies
 [2] 38145                                       
 [3] 48767                                       
 [4] 58121                                       
 [5] 64552                                       
 [6] 65883                                       
 [7] 63425                                       
 [8] 57520                                       
 [9] 61479                                       
[10] 44817                                       
[11] 48092                                       
[12] 46093                                       
12 Levels: 38145 44817 46093 48092 48767 57520 58121 61479 63425 64552 ... Net Ingredient Cost of All Pharmacotherapies
> ggplot(my.data.frame2, aes(x = prescriptions, y = ingredient))
Error in snapshot.size * 1024 : non-numeric argument to binary operator
> prov.quit()

**Comment by blernermhc** [comment] 2020-06-22 18:52
Duplicate of issue 628.

**Closed by blernermhc** 2020-06-22 18:52 UTC
