### ISSUE TITLE
Drug crimes snapshot size error in Rmd

### ISSUE THREAD

**Issue by Ranjanirr** [End-to-end-provenance/RDataTracker#622] opened 2020-06-02 18:45 UTC
> ##please be nice with me and my code. i know it's inefficient,i'm tring to improve
> ##my knowledge of R. any tips will be appreciated
> 
> train <- read.csv("train.csv")
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> library(tidyr)
> library(reshape2)
> library(stringr)
> library(plyr)
> library(dplyr)
> library(ggplot2)
> 
> newtrain<-subset(train,Category=="DRUG/NARCOTIC")
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> 
> 
> #try to have a variable dates that stores only year
> 
> split<-str_split(newtrain$Dates,"-")
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> split2<-vector("numeric")
> for( i in 1:length(newtrain$Dates))
+ {split2[i]<-split[[i]][1]}
Error in snapshot.size * 1024 : non-numeric argument to binary operator

**Comment by Ranjanirr** [comment] 2020-06-08 14:14
Kaggle = aggregating top drug crimes

**Comment by blernermhc** [comment] 2020-06-22 19:03
Duplicate of issue #628

**Closed by blernermhc** 2020-06-22 19:03 UTC
