### ISSUE TITLE
Sourced script names in console mode

### ISSUE THREAD

**Issue by fong22e** [End-to-end-provenance/RDataTracker#621] opened 2020-05-31 03:42 UTC
In the following case:
```
library(rdtLite)
prov.init(prov.dir = "testdata", snapshot.size="10")
prov.source("testscripts/sourcedScript.R")
prov.quit()
```
The script number for `sourcedScript.R` is recorded as 1, but the script name is not recorded anywhere.

**Comment by blernermhc** [comment] 2020-06-24 21:37
The problem is that when a single script is source'd, it ends up in slot 0 of the script table.  When outputting the JSON, this is considered the main script and doesn't show up.  Notably, if 2 scripts are sourced, the second one shows up.
```
library(rdtLite)
prov.init(prov.dir = ".", snapshot.size="10")
prov.source("sourcedScript.R")
prov.source("sourcedScript2.R")
prov.quit()
```
We should

**Comment by blernermhc** [comment] 2020-06-26 20:18
Fixed in commit https://github.com/End-to-end-provenance/RDataTracker/commit/a044dc548e18d28a8de1776a05c6659645373656

**Closed by blernermhc** 2020-06-26 20:18 UTC
Labels: bug
